application: ss12-gps-child-tracker
version: 1
runtime: python
api_version: 1

handlers:
- url: /gen/.*
  script: geoserv.py
- url: /GID/.*
  script: io.py
- url: /locate
  script: locator.py
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /.*
  script: html.py

